### PR TITLE
Qt6-compatible windows-support draft-request

### PR DESCRIPTION
**Pull request by mission-wuiyu**
I am very interested in this project, and I am very happy to meet a big guy who shares those great ideas and goals with me. However, the installation package of Windows version has not been compiled for this project, and this problem is also seen in the issue. It took me several days to catch some little bugs. Fortunately, the program ran normally. However, since I am not very familiar with Qt and Cpp, there are still some problems that have not been solved.

The reason for failing to compile under Windows: the project platform is 5.15? The compatibility of qt5/6, and some differences caused by the system platform.

This is my first time to participate in Qt project collaboration. Please forgive me for some immature changes and hope that they will be helpful to the project.

### CODE REVIEW

**Comment by CSMathematics** [comment]
I'm happy too to meet and work with with someone who likes this project. First of all I would like to tell you that since the last branch update I made a year ago, there have been some major improvements. In the image below you can see the current version of DataTex, which I haven't upload yet. I have a lot changes and new features in mind. Before I merge your commit (thank you very much for your efford), I would like some time to test it, and I would also like to discuss with you about the new version if you want, share the ideas, the feautres I would like to add etc so if any changes are going to be made, they will be added to the new version.


DataTex_1
DataTex_2
DataTex_3

**Comment by mission-wuiyu** [comment]
WoW, it is so beautiful and elegant, and I am looking forward to the birth of the new version. I will follow this project and will test and try it out as soon as the new version is released. I look forward to making some contributions to this project. (Whispering, maybe I can help make a Chinese translation (- V -)

**Comment by CSMathematics** [comment]
Of course you can make the Chinese translation. I think I will be able to upload the new version next month. Its not ready yet but I will try to upload it in a way so you can work with.

**Comment by mission-wuiyu** [comment]
GREAT!👍

**Pull request merged**
